/*
 * Camera_consts.h
 *
 *  Created on: Sep 19, 2018
 *      Author: peter
 */

#ifndef STEREO_WEBCAM_DEPTH_DETECTION_SOURCE_CODE_OPENCVPROJECT_CAMERA_CONSTS_H_
#define STEREO_WEBCAM_DEPTH_DETECTION_SOURCE_CODE_OPENCVPROJECT_CAMERA_CONSTS_H_

/**
参考<相机位置标定_0917_1.0.vsdx>
参数（x,y,z）为相机检测到的人的具体坐标情况。z即为文档中对应的d1
DISP_SCREEN_WIDTH 显示区域的宽度，对应文档中的Ws
DISP_SCREEN_HEIGHT 显示区域的高度，对应文档中的Hs
CAPTURE_CAMERA_HEIGHT 外拍相机的中心点到显示屏幕顶端的距离，d对应文档中的Hc
CAMERA_IMAGE_DISTANCE 相机成像的假定距离，对应文档中的d2
X_AXIS_PIXEL_SIZE X轴方向像素大小
Y_AXIS_PIXEL_SIZE y轴方向像素大小
HORIZON_VIEW_ANGLE 横向可视角的一半 对应文档中的B角度
HORIZON_VIEW_ANGLE 纵向可视角的一半 对应文档中的a角度



**/
#define PI 3.1415926

#define DISP_SCREEN_HORIZON_PIXELS 1960
#define DISP_SCREEN_VERTICAL_PIXELS 1080

#define DISP_AREA_WIDTH 20.4
#define DISP_AREA_LEFTMOST_X_COODINATE 584
#define DISP_AREA_UPMOST_Y_COODINATE 0
#define DISP_AREA_HORIZON_PIXELS 960
#define DISP_AREA_VERTICAL_PIXELS 720

#define CAPTURE_CAMERA_HEIGHT 5.8
#define CAMERA_IMAGE_DISTANCE 100.0
#define CAMERA_X_AXIS_PIXEL_SIZE 640
#define CAMERA_Y_AXIS_PIXEL_SIZE 480
#define HORIZON_VIEW_ANGLE 26*PI/180   //b
#define VERTICAL_VIEW_ANGLE 13.5*PI/180   //a



#endif /* STEREO_WEBCAM_DEPTH_DETECTION_SOURCE_CODE_OPENCVPROJECT_CAMERA_CONSTS_H_ */
